### ISSUE TITLE
Flags and Options issues

### ISSUE THREAD

**Issue by subz390** [nebrelbug/rollup-plugin-closure-compile#1]
With reference to [Flags and Options](https://github.com/google/closure-compiler/wiki/Flags-and-Options) I don't know whether I'm doing anything wrong but I can't get any of the flags except `compilation_level` to produce results.
Here is my rollup plugins object which should all work but only `compilation_level` seems to work.
```js
  plugins: [
    compile({
      // https://github.com/google/closure-compiler/wiki/Flags-and-Options
      compilation_level: 'ADVANCED', // WHITESPACE_ONLY, SIMPLE (default), ADVANCED
      formatting: 'PRETTY_PRINT',
      warning_level: 'VERBOSE', // QUIET, DEFAULT, VERBOSE
      language_out: 'ECMASCRIPT6',
      create_source_map: 'bundle.map.js',
    }),
  ],
```

**Comment by nebrelbug** [comment]
Hi @subz390, thanks for the question!

A few quick things I noticed:

I believe `ECMASCRIPT6` should be changed to `ECMASCRIPT_2015`
Sourcemaps should be set inside the Rollup configuration file, not Closure-Compiler, like:

```js
  input: 'src/index.js',
  output: {
    file: 'dist/squirrelly.min.js',
    format: 'umd',
    name: 'library',
    sourcemap: true
  },
  plugins: [
    uglify()
  ]
```

Does this help you with those 2 issues?

**Comment by nebrelbug** [comment]
@subz390 Actually, check out this link: https://github.com/google/closure-compiler-js/blob/master/README.md

Try putting all of the names in camelCase, like:

```js
{
        languageOut: 'ECMASCRIPT6',
        compilationLevel: 'ADVANCED',
        warningLevel: 'VERBOSE',
}
```

The `formatting` tag may not be supported in JS, I'll take a look

**Comment by subz390** [comment]
I see `sourcemap` in the output object, thanks.
You're also correct about `ECMASCRIPT_2015` a mistake on my part, however it seems that the output is defaulting to ES5 regardless which was originally confusing.  So `language_out` may work, it's just not given an opportunity to.
```js
`${j}-${i}=${subtract(j, i)}\n`;  // ES6 type input
j+"-"+i+"="+subtract(j,i)+"\n"; // is always converted to ES5 output
```
I'll close the issue now thanks. :thumbsup:
